import Link from 'next/link'
import { Download, RefreshCcw } from 'lucide-react'
import { requireSuperAdmin } from '@/lib/auth'
import { isBackupCenterConfigured, listBackupArtifacts } from '@/lib/github-backups'
import { PageHeader } from '@/components/layout/page-header'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'

export const dynamic = 'force-dynamic'

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  const kb = bytes / 1024
  if (kb < 1024) return `${kb.toFixed(1)} KB`
  const mb = kb / 1024
  if (mb < 1024) return `${mb.toFixed(1)} MB`
  const gb = mb / 1024
  return `${gb.toFixed(2)} GB`
}

function formatCadence(cadence: string) {
  switch (cadence) {
    case 'daily':
      return 'Daily'
    case 'weekly':
      return 'Weekly'
    case 'monthly':
      return 'Monthly'
    case 'manual':
      return 'Manual'
    default:
      return 'Unknown'
  }
}

export default async function BackupsPage() {
  await requireSuperAdmin()

  const configured = isBackupCenterConfigured()
  const artifacts = configured ? await listBackupArtifacts(100) : []

  return (
    <div>
      <PageHeader title="Backups" description="Download database backups from automated GitHub Actions runs.">
        <Button asChild variant="outline" size="sm">
          <Link href="/admin/backups">
            <RefreshCcw className="mr-2 h-4 w-4" />
            Refresh
          </Link>
        </Button>
      </PageHeader>

      <Card className="mt-6">
        <CardHeader>
          <CardTitle>Database backup artifacts</CardTitle>
          <CardDescription>
            Daily, weekly, and monthly backups are generated by workflow and available as downloadable ZIP artifacts.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {!configured ? (
            <div className="rounded-lg border border-dashed bg-muted/30 p-4 text-sm text-muted-foreground">
              Configure <code>GITHUB_BACKUP_REPO</code> and <code>GITHUB_BACKUP_TOKEN</code> in Vercel to enable backup listing and download links.
            </div>
          ) : artifacts.length === 0 ? (
            <div className="rounded-lg border border-dashed bg-muted/30 p-4 text-sm text-muted-foreground">
              No backup artifacts found yet. Run the backup workflow once from GitHub Actions.
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Name</TableHead>
                  <TableHead>Cadence</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead>Expires</TableHead>
                  <TableHead>Size</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {artifacts.map((artifact) => (
                  <TableRow key={artifact.id}>
                    <TableCell className="font-medium">{artifact.name}</TableCell>
                    <TableCell>
                      <Badge variant="secondary">{formatCadence(artifact.cadence)}</Badge>
                    </TableCell>
                    <TableCell>{new Date(artifact.createdAt).toLocaleString()}</TableCell>
                    <TableCell>{new Date(artifact.expiresAt).toLocaleString()}</TableCell>
                    <TableCell>{formatBytes(artifact.sizeBytes)}</TableCell>
                    <TableCell className="text-right">
                      <div className="flex items-center justify-end gap-2">
                        {artifact.runUrl && (
                          <Button asChild variant="ghost" size="sm">
                            <a href={artifact.runUrl} target="_blank" rel="noreferrer">
                              View run
                            </a>
                          </Button>
                        )}
                        <Button asChild size="sm" disabled={artifact.expired}>
                          <a href={`/api/admin/backups/${artifact.id}`}>
                            <Download className="mr-2 h-4 w-4" />
                            {artifact.expired ? 'Expired' : 'Download'}
                          </a>
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
